import Head from "next/head";
import Link from "next/link";

import { ArrowRightIcon } from "@heroicons/react/20/solid";

import ReactLogo from "@/components/ReactLogo";
import { ThemeSwitcher } from "@/lib/theme";

export default function Home() {
	return (
		<>
			<Head>
				<title>Taller de React</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="font-bold text-6xl underline decoration-primary decoration-wavy underline-offset-4 my-8">
				Taller de React
			</h1>
			<div className="flex gap-2">
				<Link href="/slides/01-introduction/" className="btn flex gap-1">
					Ir a las diapositivas
					<ArrowRightIcon className="w-5 h-5" />
				</Link>
				<ThemeSwitcher />
			</div>
			<ReactLogo className="-z-10 h-96 fill-primary stroke-primary absolute bottom-5 right-2 animate-[spin_8s_linear_infinite]" />
		</>
	);
}
