import Head from "next/head";
import Link from "next/link";

import { ArrowRightIcon } from "@heroicons/react/20/solid";

import ReactLogo from "@/components/ReactLogo";
import { ThemeSwitcher } from "@/lib/theme";

export default function Home() {
	return (
		<>
			<Head>
				<title>Taller de React</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="my-8 text-6xl font-bold underline decoration-primary decoration-wavy underline-offset-4">
				Taller de React
			</h1>
			<div className="flex gap-2">
				<Link href="/slides/01-intro/" className="btn flex gap-1">
					Ir a las diapositivas
					<ArrowRightIcon className="h-5 w-5" />
				</Link>
				<ThemeSwitcher />
			</div>
			<ReactLogo className="absolute bottom-5 right-2 -z-10 h-96 animate-[spin_8s_linear_infinite] fill-primary stroke-primary" />
		</>
	);
}
